// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDluY_lOe3U5QKagWwpgTWi6IYainCQfSc',
    appId: '1:1006387293237:web:db79b135c6f06b21ea557c',
    messagingSenderId: '1006387293237',
    projectId: 'quizflutter-5d1e0',
    authDomain: 'quizflutter-5d1e0.firebaseapp.com',
    storageBucket: 'quizflutter-5d1e0.firebasestorage.app',
    measurementId: 'G-P8SDX3WQ40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvHQP9cmE0UjVXryyZTl2iRE0mQTbZV2c',
    appId: '1:1006387293237:android:c982a5239e5c5673ea557c',
    messagingSenderId: '1006387293237',
    projectId: 'quizflutter-5d1e0',
    storageBucket: 'quizflutter-5d1e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC07zM9DSLIeD4WMf8EkqB9-KS9kT3sYTU',
    appId: '1:1006387293237:ios:7a0c75d1c83702dbea557c',
    messagingSenderId: '1006387293237',
    projectId: 'quizflutter-5d1e0',
    storageBucket: 'quizflutter-5d1e0.firebasestorage.app',
    iosBundleId: 'com.example.flutterQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC07zM9DSLIeD4WMf8EkqB9-KS9kT3sYTU',
    appId: '1:1006387293237:ios:7a0c75d1c83702dbea557c',
    messagingSenderId: '1006387293237',
    projectId: 'quizflutter-5d1e0',
    storageBucket: 'quizflutter-5d1e0.firebasestorage.app',
    iosBundleId: 'com.example.flutterQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDluY_lOe3U5QKagWwpgTWi6IYainCQfSc',
    appId: '1:1006387293237:web:466354f06c7ba299ea557c',
    messagingSenderId: '1006387293237',
    projectId: 'quizflutter-5d1e0',
    authDomain: 'quizflutter-5d1e0.firebaseapp.com',
    storageBucket: 'quizflutter-5d1e0.firebasestorage.app',
    measurementId: 'G-D0CQCMYK98',
  );
}
